### ISSUE TITLE
unable to run Tomcat server

### ISSUE THREAD

**Issue by tiburona** [NrgXnat/xnat-docker-compose#18]
@johnflavin I'm excited to take advantage of your project.  I'd like to get an xnat instance up on my machine to experiment with before I use my lab's XNAT server.  

Right now I'm unable to run Tomcat.  I follow steps 1-4 but localhost/xnat responds with 404.  When I look at the logs with `docker-compose logs -f --tail=20 xnat-web` I see the following error:

`java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/xnat]]
xnat-web_1    | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1019)
xnat-web_1    | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:991)
xnat-web_1    | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
xnat-web_1    | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
xnat-web_1    | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
xnat-web_1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
xnat-web_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
xnat-web_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
xnat-web_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
xnat-web_1    | 	at java.lang.Thread.run(Thread.java:745)
xnat-web_1    | 
xnat-web_1    | Apr 11, 2018 9:19:03 PM org.apache.catalina.startup.HostConfig deployWAR
xnat-web_1    | INFO: Deployment of web application archive /opt/tomcat/webapps/xnat.war has finished in 140 ms
xnat-web_1    | Apr 11, 2018 9:19:03 PM org.apache.coyote.AbstractProtocol start
xnat-web_1    | INFO: Starting ProtocolHandler ["http-bio-8080"]
xnat-web_1    | Apr 11, 2018 9:19:03 PM org.apache.coyote.AbstractProtocol start
xnat-web_1    | INFO: Starting ProtocolHandler ["ajp-bio-8009"]
xnat-web_1    | Apr 11, 2018 9:19:03 PM org.apache.catalina.startup.Catalina start
xnat-web_1    | INFO: Server startup in 381 ms
`
(One thing I was a little unclear on from the readme was the appropriate location of the .war file.  Right now I have redundant copies both in a webapp dir that's sibling to the ngingx, postgres etc. direrectories, and in a webapp dir that's sibling to the xnat-docker-compose-directory. )

Thanks for considering this issue!

**Comment by mattsouth** [comment]
HI @tiburona - if you followed the readme there's a chance you didnt actually download the correct xnat.war (I think the url may have changed since the last time the readme was updated).  The latest xnat.war file is 184MB and available from https://api.bitbucket.org/2.0/repositories/xnatdev/xnat-web/downloads/xnat-web-1.7.4.1.war - I looked at https://download.xnat.org/ to check this.

**Comment by mattsouth** [comment]
PS I think the readme also needs an adjustment re: the location of the webapps directory which I believe is a subdirectory you need to create under the xnat-docker-compose directory.

**Comment by tiburona** [comment]
Thank you @mattsouth.  I don't know if it would be appropriate to start a new issue about this, but I deleted the repo and started again based on the updated instructions you provided (I just figured it was safer to start from the very beginning), and I have definitely made process, in that a web application is served but all it renders is this error message (which made me laugh out loud):

`Horrible Exception: org.apache.commons.configuration.ConfigurationException: Cannot locate configuration source /opt/tomcat/WEB-INF/conf/TurbineResources.properties`

**Comment by mattsouth** [comment]
I havent ever seen this myself, though it occasionally comes up on the discussion group, e,g:
* https://groups.google.com/forum/#!topic/xnat_discussion/ufXAuCFWeDY
* https://groups.google.com/forum/#!topic/xnat_discussion/5abcu9c43sw
* https://wiki.xnat.org/display/XNAT17/Configuring+Tomcat+To+Avoid+Errors
It seems its a tomcat issue.  Is the missing file there?  After a fresh install I see it in  ``webapps/xnat/WEB-INF/conf/`` where  I see a text file with 26396 bytes that was last updated on Jul 6 2017.
