### ISSUE TITLE
Change weight and height units

### ISSUE THREAD

**Issue by rgllm** [NrgXnat/xnat-docker-compose#22]
Any way to change weight unit from lbs to kgs and height units to cm?

Sorry if this is not the correct place to ask this.

Thanks.

**Comment by johnflavin** [comment]
This sounds more like an XNAT configuration question and less like a question about running XNAT with `docker-compose`. As such, I think this question is better for the [xnat_discussion google group](https://groups.google.com/forum/#!forum/xnat_discussion). 

Thanks for asking! Sorry I don't know how to help.
