### ISSUE TITLE
Project Owner error message

### ISSUE THREAD

**Issue by bkossows** [NrgXnat/xnat-docker-compose#26]
When project owner wants to access the project there is an error message 403 "The user XX is not allowed to access this information". One cannot also add/edit other project access settings. However, owners with "All data access" do not have such problems.

**Comment by rherrick** [comment]
Unable to reproduce. If reproducible, this would be an error in XNAT itself and can be reported on the [XNAT JIRA](https://issues.xnat.org) or by sending email to bugs@xnat.org.
