### ISSUE TITLE
Replace manishkumr/ubuntu_jdk7_image base tomcat7 base container

### ISSUE THREAD

**Issue by tclose** [NrgXnat/xnat-docker-compose#3]
It would be good to replace the manishkumr/ubuntu_jdk7_image base with a new image built from a dockerfile

**Comment by rsingh5** [comment]
ENV TOMCAT_MAJOR 7
ENV TOMCAT_VERSION 7.0.82
# Get Tomcat
ENV TOMCAT_TGZ_URLS \
# https://issues.apache.org/jira/browse/INFRA-8753?focusedCommentId=14735394#comment-14735394
        https://www.apache.org/dyn/closer.cgi?action=download&filename=tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz \
# if the version is outdated, we might have to pull from the dist/archive :/
        https://www-us.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz \
        https://www.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz \
        https://archive.apache.org/dist/tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz

RUN set -eux; \
        \
        success=; \
        for url in $TOMCAT_TGZ_URLS; do \
                if wget -O /tmp/tomcat.tar.gz "$url"; then \
                        success=1; \
                        break; \
                fi; \
        done; \
        [ -n "$success" ]; \

#RUN wget --quiet --no-cookies http://apache.mirror.digitalpacific.com.au/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -O /tmp/tomcat.tgz && \
tar xzvf /tmp/tomcat.tar.gz -C /opt && \
mv /opt/apache-tomcat-${TOMCAT_VERSION} /opt/tomcat && \
rm /tmp/tomcat.tar.gz && \

**Comment by Sikerdebaard** [comment]
Working on this. Can't seems to assign myself to this issue.

**Comment by Sikerdebaard** [comment]
https://github.com/NrgXnat/xnat-docker-compose/pull/6
