### ISSUE TITLE
Unable to create new users

### ISSUE THREAD

**Issue by adbartni** [NrgXnat/xnat-docker-compose#31]
Just cloned the repo and started building, only change was to add alpine-9.4.25 in the postgres Dockerfile.

The database builds and the web server starts, and clicking create user takes me to the user creation page. The issue is that when I go to submit my new user, I get an error at the top of the page saying, "Email send failed. If you cannot login contact you administrator."

I can upload the output of `docker-compose up` if need be.

Thanks in advance.

**Comment by kelseym** [comment]
That would be helpful. Please also include any xnat log output - from the xnat-data/logs or xnat-data/home/logs folder.

**Comment by adbartni** [comment]
Here's the output form `docker-compose up`

`Building xnat-db
Step 1/2 : FROM postgres:9.4.25-alpine
9.4.25-alpine: Pulling from library/postgres
c9b1b535fdd9: Already exists
d1030c456d04: Already exists
d1d0211bbd9a: Already exists
7770fe83b180: Pull complete
94fef6b8e648: Pull complete
416de68c3c63: Pull complete
89ed5c16a3b0: Pull complete
4b29341985be: Pull complete
a2375facf436: Pull complete
Digest: sha256:77b9ed89c77b1fd279cab01b6da1b3fa25fa6b56bde61454d4e9899f92e2d498
Status: Downloaded newer image for postgres:9.4.25-alpine
 ---> b4f710a5561e
Step 2/2 : COPY XNAT.sql /docker-entrypoint-initdb.d/
 ---> 790f1c7919ba
Successfully built 790f1c7919ba
Successfully tagged docker_xnat-db:latest
Building xnat-web
Step 1/17 : FROM tomcat:7-jre8-alpine
 ---> d3deaf2d7b68
Step 2/17 : MAINTAINER Matt Kelsey <kelseym@wustl.edu>
 ---> Using cache
 ---> 03cd8dac84cc
Step 3/17 : ARG XNAT_VER
 ---> Using cache
 ---> d72f40ae79de
Step 4/17 : ARG XNAT_ROOT=/data/xnat
 ---> Using cache
 ---> feef4a4841ec
Step 5/17 : ARG XNAT_HOME=/data/xnat/home
 ---> Using cache
 ---> 7a92f42b1762
Step 6/17 : ARG XNAT_DATASOURCE_DRIVER=org.postgresql.Driver
 ---> Using cache
 ---> 2418ce8102a3
Step 7/17 : ARG XNAT_DATASOURCE_URL=jdbc:postgresql://xnat-db/xnat
 ---> Using cache
 ---> aab1417f5232
Step 8/17 : ARG XNAT_DATASOURCE_USERNAME=xnat
 ---> Using cache
 ---> 629cd3d8d438
Step 9/17 : ARG XNAT_DATASOURCE_PASSWORD=xnat
 ---> Using cache
 ---> 68f683389ecf
Step 10/17 : ARG XNAT_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL9Dialect
 ---> Using cache
 ---> da8a6dc80ad1
Step 11/17 : ARG TOMCAT_XNAT_FOLDER=ROOT
 ---> Using cache
 ---> 2ea0bc4e70a7
Step 12/17 : ADD make-xnat-config.sh /usr/local/bin/make-xnat-config.sh
 ---> Using cache
 ---> 2515624cd468
Step 13/17 : ADD wait-for-postgres.sh /usr/local/bin/wait-for-postgres.sh
 ---> Using cache
 ---> 9033eb9822e6
Step 14/17 : RUN apk add --no-cache         postgresql-client         wget     &&     rm -rf $CATALINA_HOME/webapps/* &&     mkdir -p         $CATALINA_HOME/webapps/${TOMCAT_XNAT_FOLDER}         ${XNAT_HOME}/config         ${XNAT_HOME}/logs         ${XNAT_HOME}/plugins         ${XNAT_HOME}/work         ${XNAT_ROOT}/archive         ${XNAT_ROOT}/build         ${XNAT_ROOT}/cache         ${XNAT_ROOT}/ftp         ${XNAT_ROOT}/pipeline         ${XNAT_ROOT}/prearchive     &&     /usr/local/bin/make-xnat-config.sh &&     rm /usr/local/bin/make-xnat-config.sh &&     cd $CATALINA_HOME/webapps/ &&     wget https://api.bitbucket.org/2.0/repositories/xnatdev/xnat-web/downloads/xnat-web-${XNAT_VER}.war &&     cd ${TOMCAT_XNAT_FOLDER} &&     unzip -o ../xnat-web-${XNAT_VER}.war &&     rm -f ../xnat-web-${XNAT_VER}.war &&     apk del wget
 ---> Using cache
 ---> fcd03eb5ce66
Step 15/17 : EXPOSE 8080
 ---> Using cache
 ---> c540a25ca542
Step 16/17 : ENV XNAT_HOME=${XNAT_HOME} XNAT_DATASOURCE_USERNAME=${XNAT_DATASOURCE_USERNAME}
 ---> Using cache
 ---> c1347ad360d1
Step 17/17 : CMD ["wait-for-postgres.sh", "/usr/local/tomcat/bin/catalina.sh", "run"]
 ---> Using cache
 ---> 11d9e4190608
Successfully built 11d9e4190608
Successfully tagged docker_xnat-web:latest
Building xnat-nginx
Step 1/3 : FROM nginx:1.12-alpine-perl
 ---> b6a456f1d7ae
Step 2/3 : RUN rm /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> 28f40513e2af
Step 3/3 : COPY nginx.conf /etc/nginx
 ---> Using cache
 ---> dad433bb5364
Successfully built dad433bb5364
Successfully tagged docker_xnat-nginx:latest
Recreating docker_xnat-db_1 ... 
Recreating docker_xnat-db_1 ... done
Recreating docker_xnat-web_1 ... 
Recreating docker_xnat-web_1 ... done
Recreating docker_xnat-nginx_1 ... 
Recreating docker_xnat-nginx_1 ... done
Attaching to docker_xnat-db_1, docker_xnat-web_1, docker_xnat-nginx_1
xnat-web_1    | Postgres is up - executing command "/usr/local/tomcat/bin/catalina.sh run"
xnat-db_1     | 
xnat-db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
xnat-web_1    | Listening for transport dt_socket at address: 8000
xnat-db_1     | 
xnat-db_1     | LOG:  database system was shut down at 2020-05-29 20:27:11 UTC
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Server version:        Apache Tomcat/7.0.94
xnat-db_1     | LOG:  MultiXact member wraparound protections are now enabled
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Server built:          Apr 10 2019 16:56:40 UTC
xnat-db_1     | LOG:  database system is ready to accept connections
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-db_1     | LOG:  autovacuum launcher started
xnat-web_1    | INFO: Server number:         7.0.94.0
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: OS Name:               Linux
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: OS Version:            4.15.0-88-generic
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Architecture:          amd64
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Java Home:             /usr/lib/jvm/java-1.8-openjdk/jre
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: JVM Version:           1.8.0_212-b04
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: JVM Vendor:            IcedTea
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: CATALINA_BASE:         /usr/local/tomcat
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: CATALINA_HOME:         /usr/local/tomcat
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Xms128m
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Xmx2048m
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Dxnat.home=/data/xnat/home
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Dignore.endorsed.dirs=
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Dcatalina.base=/usr/local/tomcat
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Dcatalina.home=/usr/local/tomcat
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.startup.VersionLoggerListener log
xnat-web_1    | INFO: Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
xnat-web_1    | INFO: Loaded APR based Apache Tomcat Native library 1.2.21 using APR version 1.6.5.
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
xnat-web_1    | INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
xnat-web_1    | May 29, 2020 8:28:51 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
xnat-web_1    | INFO: OpenSSL successfully initialized (OpenSSL 1.1.1b  26 Feb 2019)
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.coyote.AbstractProtocol init
xnat-web_1    | INFO: Initializing ProtocolHandler ["http-apr-8080"]
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.coyote.AbstractProtocol init
xnat-web_1    | INFO: Initializing ProtocolHandler ["ajp-apr-8009"]
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.catalina.startup.Catalina load
xnat-web_1    | INFO: Initialization processed in 1771 ms
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.catalina.core.StandardService startInternal
xnat-web_1    | INFO: Starting service Catalina
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.catalina.core.StandardEngine startInternal
xnat-web_1    | INFO: Starting Servlet Engine: Apache Tomcat/7.0.94
xnat-web_1    | May 29, 2020 8:28:52 PM org.apache.catalina.startup.HostConfig deployDirectory
xnat-web_1    | INFO: Deploying web application directory /usr/local/tomcat/webapps/ROOT
xnat-web_1    | May 29, 2020 8:29:05 PM org.apache.catalina.startup.TldConfig execute
xnat-web_1    | INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
xnat-db_1     | ERROR:  relation "activemq_msgs" already exists
xnat-db_1     | STATEMENT:  CREATE TABLE ACTIVEMQ_MSGS(ID BIGINT NOT NULL, CONTAINER VARCHAR(250), MSGID_PROD VARCHAR(250), MSGID_SEQ BIGINT, EXPIRATION BIGINT, MSG BYTEA, PRIMARY KEY ( ID ) )
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE INDEX ACTIVEMQ_MSGS_MIDX ON ACTIVEMQ_MSGS (MSGID_PROD,MSGID_SEQ)
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE INDEX ACTIVEMQ_MSGS_CIDX ON ACTIVEMQ_MSGS (CONTAINER)
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE INDEX ACTIVEMQ_MSGS_EIDX ON ACTIVEMQ_MSGS (EXPIRATION)
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE TABLE ACTIVEMQ_ACKS(CONTAINER VARCHAR(250) NOT NULL, SUB_DEST VARCHAR(250), CLIENT_ID VARCHAR(250) NOT NULL, SUB_NAME VARCHAR(250) NOT NULL, SELECTOR VARCHAR(250), LAST_ACKED_ID BIGINT, PRIMARY KEY ( CONTAINER, CLIENT_ID, SUB_NAME))
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE TABLE ACTIVEMQ_LOCK( ID BIGINT NOT NULL, TIME BIGINT, BROKER_NAME VARCHAR(250), PRIMARY KEY (ID) )
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  INSERT INTO ACTIVEMQ_LOCK(ID) VALUES (1)
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_MSGS ADD PRIORITY BIGINT
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  CREATE INDEX ACTIVEMQ_MSGS_PIDX ON ACTIVEMQ_MSGS (PRIORITY)
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_MSGS ADD XID BYTEA
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_ACKS ADD PRIORITY BIGINT DEFAULT 5 NOT NULL
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_ACKS ADD XID BYTEA
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_ACKS DROP CONSTRAINT "activemq_acks_pkey"
xnat-db_1     | ERROR:  current transaction is aborted, commands ignored until end of transaction block
xnat-db_1     | STATEMENT:  ALTER TABLE ACTIVEMQ_ACKS ADD PRIMARY KEY (CONTAINER, CLIENT_ID, SUB_NAME, PRIORITY)
xnat-web_1    | SOURCE: /usr/local/tomcat/webapps/ROOT/
xnat-web_1    | Database up to date.
xnat-web_1    | May 29, 2020 8:30:17 PM org.apache.catalina.startup.HostConfig deployDirectory
xnat-web_1    | INFO: Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 85,397 ms
xnat-web_1    | May 29, 2020 8:30:17 PM org.apache.coyote.AbstractProtocol start
xnat-web_1    | INFO: Starting ProtocolHandler ["http-apr-8080"]
xnat-web_1    | May 29, 2020 8:30:17 PM org.apache.coyote.AbstractProtocol start
xnat-web_1    | INFO: Starting ProtocolHandler ["ajp-apr-8009"]
xnat-web_1    | May 29, 2020 8:30:17 PM org.apache.catalina.startup.Catalina start
xnat-web_1    | INFO: Server startup in 85509 ms
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker_xnat-nginx_1 ... done
Stopping docker_xnat-web_1   ... done
Stopping docker_xnat-db_1    ... done`

And here's what I believe is the relevant bit from xnat-data/home/logs/xdat.log

`Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
	at javax.mail.Service.connect(Service.java:366)
	at org.springframework.mail.javamail.JavaMailSenderImpl.connectTransport(JavaMailSenderImpl.java:503)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:422)
	... 99 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
	... 103 common frames omitted`

I'm guessing there's a confirmation link in the email XNAT sends that a new user needs to click, but since that email isn't being sent it's not finalizing new users. I can't attempt to create a user with the same email or username more than once.

**Comment by kelseym** [comment]
Yes, that's exactly right.  Have you setup an email server?
https://wiki.xnat.org/display/XNAT17/XNAT+Email+Server+Settings+in+the+Admin+UI

**Comment by adbartni** [comment]
No, I'm unable to get to any admin settings. I'm only presented with the login screen and options to register an account or reset a password.

**Comment by adbartni** [comment]
Didn't realize the default password was admin, my mistake.

**Comment by kelseym** [comment]
Great. Glad you got it sorted out.  Another good resource for general XNAT questions is our Google group:
https://groups.google.com/forum/#!forum/xnat_discussion
