### ISSUE TITLE
xnat-web: build error: bin/sh

### ISSUE THREAD

**Issue by kavijoshi92** [NrgXnat/xnat-docker-compose#36]
Hi
while building xnat-web in docker i am getting the following error. Please advise

/bin/sh: /usr/local/bin/make-xnat-config.sh: not found
ERROR: Service 'xnat-web' failed to build: The command '/bin/sh -c apk add --no-cache         postgresql-client         wget     &&     rm -rf $CATALINA_HOME/webapps/* &&     mkdir -p         $CATALINA_HOME/webapps/${TOMCAT_XNAT_FOLDER}         ${XNAT_HOME}/config         ${XNAT_HOME}/logs         ${XNAT_HOME}/plugins         ${XNAT_HOME}/work         ${XNAT_ROOT}/archive         ${XNAT_ROOT}/build         ${XNAT_ROOT}/cache         ${XNAT_ROOT}/ftp         ${XNAT_ROOT}/pipeline         ${XNAT_ROOT}/prearchive &&     /usr/local/bin/make-xnat-config.sh    &&     rm /usr/local/bin/make-xnat-config.sh &&     cd $CATALINA_HOME/webapps/ &&     wget https://api.bitbucket.org/2.0/repositories/xnatdev/xnat-web/downloads/xnat-web-${XNAT_VER}.war &&     cd ${TOMCAT_XNAT_FOLDER} &&     unzip -o ../xnat-web-${XNAT_VER}.war &&     rm -f ../xnat-web-${XNAT_VER}.war &&     apk del wget' returned a non-zero code: 127

**Comment by rherrick** [comment]
We need more detail on your environment–especially platform and versions of Docker and docker-compose–and which branch of xnat-docker-compose you’re trying to build.

--
Rick Herrick
Sr. Programmer/Analyst
Neuroinformatics Research Group
Washington University School of Medicine
Phone: +1 (314) 273-1645

**Comment by rherrick** [comment]
Try updating to the latest commit on the **master** branch of this repo, bcef869. The commands in [xnat/Dockerfile](https://github.com/NrgXnat/xnat-docker-compose/blob/master/xnat/Dockerfile) have been separated into multiple lines, so if something fails in there it should be more obvious what it is.

**Comment by JPAntonisse** [comment]
This looks like the same issue as: https://github.com/NrgXnat/xnat-docker-compose/issues/42
