### ISSUE TITLE
Work out how to add plugins

### ISSUE THREAD

**Issue by mattsouth** [NrgXnat/xnat-docker-compose#4]
We need an easy way to add plugins.

**Comment by johnflavin** [comment]
I can think of an easy way, which is to just have your plugins downloaded locally and mount that directory into the xnat container.

It would be nice to have this all managed by docker-compose, where you specify some information in the yaml file about which plugins you want and it downloads the plugin jars at `docker-compose up`. But I don't know enough about docker-compose to say if this is possible or easy.

**Comment by koekie** [comment]
You can kind of hack in hooks to docker events to do what you want, but this is not easy or straightforward, and if anything it will most probably be ugly ;)

In my opinion the best options are:

- Like Flavin said, mounting the plugins into the docker container
- Or make something in the xnat container downloading the plugins based on environment variables (like a list of download url's)

**Comment by johnflavin** [comment]
We on the XNAT team have talked about the need to manage plugins, or configure the plugins you have, or whatever. Something like, you could have some plugin manifest file with names and URLs, and when XNAT starts up it looks for those jars in your plugins directory and if it doesn't find them it downloads them from the URL. Something along those lines. But that's nascent right now, and won't be done any time soon. It has other blocking issues that also aren't possible yet, like XNAT being able to restart tomcat. 

In the meantime, a mounted directory is easy and possible now.

**Comment by rherrick** [comment]
This is supported using a Gradle build configuration and JSON manifest file in the [**features/dependency-mgmt** branch](https://github.com/NrgXnat/xnat-docker-compose/tree/features/dependency-mgmt). You can also specify the war file to be downloaded. Eventually this will be merged into the master branch and released.
