### ISSUE TITLE
[BUG] On initial deploy, site displays login screen instead of setup screen

### ISSUE THREAD

**Issue by waltman** [NrgXnat/xnat-docker-compose#40]
**Describe the bug**
The container started without any errors, but I can't login. It displays the login screen but there's no obvious way to login. Attempting to register a new user returns

> Email send failed. If you are unable to log in to your account, please contact an administrator or create an account with a different email address.

**To Reproduce**
1. Clone repository.
2. `$ docker-compose up -d`
3. Wait until the system is running.
4. Open http://localhost/
5. This takes me to http://localhost/app/template/Login.vm#!

**Expected behavior**
I'm not entirely sure since is the first time I'm trying to run XNAT. The [documentation](https://wiki.xnat.org/documentation/xnat-administration/xnat-setup-first-time-configuration) is a bit unclear about this but it sounds like it should take me to **http://<xnat_home_url>/setup**.

If I try to go to /setup directly it redirects me back to the login screen.

**Screenshots**

**Docker server environment (please complete the following information):**
 - Host OS: Ununtu 20.04
 - Docker version: 19.03.8
 - docker-compose version: 1.26.0
 - Anything else?

**Configuration:**
 - Branch of XNAT docker-compose project: master
 - Commit hash or tag: d96eaeb8939aed955388e78b9f100b25cb32fb58
 - Environment settings: [e.g. environment variables, **.env** file]
 - Configuration: [e.g. plugins, manifest, etc.]

**Additional context**
Overall what I'm trying to figure out is how to login as administrator and set up a few accounts.

**Comment by rherrick** [comment]
This is the correct behavior. You have to login first with the credentials **admin:admin**. Once logged in, XNAT will take you to the setup page automatically if the system hasn't been initialized already. I've modified the documentation to make it clear you need to log in first.
