### ISSUE TITLE
Errors during DB Initialisation

### ISSUE THREAD

**Issue by srinhari** [NrgXnat/xnat-docker-compose#41]
I get the following errors durign the xnat db initialisation (upon running docker-compose up):

xnat-db_1     | ERROR:  relation "arc_archivespecification" does not exist at character 22
xnat-db_1     | STATEMENT:  select count(*) from arc_archivespecification
xnat-web_1    | SOURCE: /usr/local/tomcat/webapps/ROOT/
xnat-web_1    | ===========================
xnat-web_1    | New Database -- BEGINNING Initialization
xnat-web_1    | ===========================
xnat-db_1     | ERROR:  relation "xdat_element_security" does not exist at character 74
xnat-db_1     | STATEMENT:  SELECT xdat_element_security.element_name AS xdat_element_security0 FROM xdat_element_security xdat_element_security
xnat-db_1     | ERROR:  relation "xdat_user" does not exist at character 28
xnat-db_1     | STATEMENT:  SELECT login, enabled FROM xdat_user WHERE login NOT IN (SELECT xdat_username FROM xhbm_xdat_user_auth)
xnat-db_1     | ERROR:  relation "xdat_usergroup" does not exist at character 30
xnat-db_1     | STATEMENT:  SELECT tag, displayname FROM xdat_usergroup WHERE tag IS NOT NULL AND substr(id, length(tag)+2) LIKE E'%\\_%'

Host: CentOS-7
Docker: 19.03

However, I am able to open up the Xnat website.

**Comment by rherrick** [comment]
That’s normal. Those queries are made by initialization tasks in XNAT. Those tasks start automatically along with other services in XNAT and, in an uninitialized system, might be querying tables and views that don’t yet exist. Those tasks catch the errors and defer execution for a period of time. They’ll keep doing that until the tables they’re trying to check exist, at which point the initialization task proceeds. In a traditional server deployment, you would only see that if you’re monitoring the database logs, but of course the docker-compose console combines the logs from all of the containers, so you get to see the messy side of how XNAT starts up 😊

Once you’ve initialized the system and the database schema is all there, you shouldn’t see those messages any more (or least not that often).

--
Rick Herrick
Sr. Programmer/Analyst
Neuroinformatics Research Group
Washington University School of Medicine
Phone: +1 (314) 273-1645

**Comment by srinhari** [comment]
Thank you rherrick for the quick reply.
