### ISSUE TITLE
[BUG] XNAT-Web failed to build on Windows

### ISSUE THREAD

**Issue by aditsanghvi94** [NrgXnat/xnat-docker-compose#42]
When i run docker-compose up, i get this error
Step 18/26 : RUN /usr/local/bin/make-xnat-config.sh
 ---> Running in 5e26f46efdcc
/bin/sh: /usr/local/bin/make-xnat-config.sh: not found
ERROR: Service 'xnat-web' failed to build: The command '/bin/sh -c /usr/local/bin/make-xnat-config.sh' returned a non-zero code: 127

**Expected behavior**
xnat spins up
**Screenshots**

**Docker server environment (please complete the following information):**
 - Host OS: Windows 
 - Docker version Docker version 19.03.12,
 docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

**Configuration:**
 - Branch of XNAT docker-compose project: master

**Comment by JPAntonisse** [comment]
@rherrick @aditsanghvi94 
**Fix for Windows**
On my Windows machine I faced the same problem, I found out that the problem is the ending of the file for Windows.
To fix the issue do the following:
`git config --global core.autocrlf false`

After this, **clone** the github project and it works!
