### ISSUE TITLE
[BUG]  tomcat:7-jre8-alpine Docker image no longer seems to be maintained upstream. 

### ISSUE THREAD

**Issue by willfurnass** [NrgXnat/xnat-docker-compose#48]
**Describe the bug**

`tomcat:7-jre8-alpine` image no longer maintained upstream.  [No Alpine-related Tomcat images updated in ~2 years](https://hub.docker.com/_/tomcat?tab=tags&page=1&ordering=last_updated&name=alpine).  Suggest switching to Debian Buster or Buster Slim-based Tomcat images. 

**To Reproduce**
1. `sudo docker-compose --pull --parallel build` 
2. `sudo trivy image --severity HIGH,CRITICAL --ignore-unfixed xnat-docker-compose_xnat-web:latest`
3. Long list of CVEs presented

**Docker server environment (please complete the following information):**
 - Host OS: Arch
 - Docker version: 20.10.5
 - docker-compose version: 1.28.5
 - Anything else?

**Configuration:**
 - Branch of XNAT docker-compose project: `master`
 - Commit hash or tag: 8534c2faa56177fe2b33f913c0f04a36dcee6ca4
 - Environment settings: defaults
 - Configuration: defaults

**Comment by kelseym** [comment]
Updated xnat-web base image to tomcat:7.0.108-jdk8-openjdk-buster
