### ISSUE TITLE
[BUG] `postgres:9.4-alpine` image no longer maintained upstream

### ISSUE THREAD

**Issue by willfurnass** [NrgXnat/xnat-docker-compose#49]
**Describe the bug**

`postgres:9.4-alpine` image no longer maintained upstream: [not updated in ~1 year](https://hub.docker.com/_/postgrest?tab=tags&page=1&ordering=last_updated&name=alpine).  Could switch to `postgres:9-alpine` if minor version increases are always straightforward or, if not, `postgres:9-6-alpine`.

**To Reproduce**
1. `sudo docker-compose --pull --parallel build` 
2. `sudo trivy image --severity HIGH,CRITICAL --ignore-unfixed xnat-docker-compose_xnat-db:latest`
3. Long list of CVEs presented

**Docker server environment (please complete the following information):**
 - Host OS: Arch
 - Docker version: 20.10.5
 - docker-compose version: 1.28.5
 - Anything else?

**Configuration:**
 - Branch of XNAT docker-compose project: `master`
 - Commit hash or tag: 8534c2faa56177fe2b33f913c0f04a36dcee6ca4
 - Environment settings: defaults
 - Configuration: defaults

**Comment by kelseym** [comment]
Updated posgres image to postgres:12.2-alpine base.
