### ISSUE TITLE
Deploy Xnat on Kubernetes Cluster

### ISSUE THREAD

**Issue by lalithvaka** [NrgXnat/xnat-docker-compose#66]
**Is your feature request related to a problem? Please describe.**
For scalability purposes and for ease of management, can we have this available as K8S deployable?

**Describe the solution you'd like**
An YAML file package with  all the dependencies assuming a functioning K8S cluster with a proxy available

**Comment by rherrick** [comment]
The closest thing we have to this at the moment is a Helm chart that I've gotten _mostly_ working. You can find that [here](https://github.com/rherrick/xnat-helm). It's very much a sandbox/playground so some of the stuff definitely isn't what you'd want for a production service, e.g. in the **features/traefik** branch, it creates three instances of the [containous/whoami](https://hub.docker.com/r/containous/whoami) container (**whoami1**, **whoami2**, and **whoami3**) just so I could verify the load-balancing function of the Traefik container. 

At this point, this isn't something I'd put under the imprimatur of an "official" XNAT-supported tool. I'm not strong with Kubernetes generally or with Helm charts in particular, so, while this does work, there are probably a _lot_ better ways to do many of the things that are in there. Have a look at it and if it's useful great and if you can contribute back any improvements or whatever then even better. Once it's working better–e.g. providing ways to customize the configuration, multi-node support, etc.–we'll promote it to an XNAT-released product.

**Comment by lalithvaka** [comment]
Thank you @rherrick . Appreciate the quick response. I have come across [this](https://github.com/Australian-Imaging-Service/charts) as well. Will try both.
