### ISSUE TITLE
Gradlew build fails for the xnat-web

### ISSUE THREAD

**Issue by lalithvaka** [NrgXnat/xnat-docker-compose#74]
**Describe the bug**

**To Reproduce**
$ git clone https://github.com/NrgXnat/xnat-docker-compose
$ cd xnat-docker-compose
$ git checkout features/dependency-mgmt
4. See error while building using gradlew and failing to build the Dockerfile under xnat-web.
```
  Step 27/31 : RUN apk add --no-cache         postgresql-client wget &&     rm -rf ${CATALINA_HOME}/webapps/* &&     mkdir -p         ${CATALINA_HOME}/webapps/${XNAT_WEBAPP_FOLDER}         ${XNAT_HOME}/config         ${XNAT_HOME}/logs         ${XNAT_HOME}/plugins         ${XNAT_HOME}/work         ${XNAT_ROOT}/archive         ${XNAT_ROOT}/build         ${XNAT_ROOT}/cache         ${XNAT_ROOT}/ftp         ${XNAT_ROOT}/pipeline         ${XNAT_ROOT}/prearchive &&     /usr/local/bin/make-xnat-config.sh &&     rm /usr/local/bin/make-xnat-config.sh
   ---> Running in 3a75c232a180
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
  WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
  ERROR: unsatisfiable constraints:
    postgresql-client (missing):
      required by: world[postgresql-client]
    wget (missing):
      required by: world[wget]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

**Expected behavior**
Build to succeed.

**Screenshots**

**Docker server environment (please complete the following information):**
 - Host OS: - RHEL 7.7
 - Docker version - 20.10.6, build 370c289
 - docker-compose version -- version 1.29.1, build c34c88b2
 - Anything else? Java 8

**Configuration:**
 - Environment settings: default
 - Configuration: .manifest-XNAT-ML-18.json

**Additional context**
The docker build with out dependency  mgmt repo is working well from https://github.com/NrgXnat/xnat-docker-compose. Also noticed xnat-web dockerfile has differences between these two branches

**Comment by rherrick** [comment]
This error is due to Docker being unable to reach the `dl-cdn.alpinelinux.org` server while building the XNAT image. There was either a network issue while you were trying to build or something in your network configuration is blocking this connection.

On the server where you're trying to run your docker-compose configuration, try downloading the failed artifact directly by doing something like:

```
wget http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
```

If that works, it was just a temporary glitch and you should be okay to try again. If you still can't reach that server, you'll have to find a way to build the Docker images outside of your execution environment and then transfer them into your Docker server. Internet access for any of the configurations in this project to work properly, as they all build on images from Docker Hub, provision images from apt or apk repos, etc.

**Comment by lalithvaka** [comment]
hi @rherrick , thank you for a quick response. if I use FROM tomcat:7.0.108-jdk8-openjdk-buster  from https://github.com/NrgXnat/xnat-docker-compose/blob/master/xnat/Dockerfile  and change RUN APK to RUN apt-get the build is successful. But my Tomcat xnat-web does  not come up  at all with  the following errors 
```
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFO: OpenSSL successfully initialized [OpenSSL 1.1.1d  10 Sep 2019]
Apr 21, 2021 4:17:05 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-apr-8080"]
Apr 21, 2021 4:17:05 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 672 ms
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Catalina]
Apr 21, 2021 4:17:05 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.108
Apr 21, 2021 4:17:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
Debugger failed to attach: handshake failed - connection prematurally closed
Apr 21, 2021 4:17:15 PM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Apr 21, 2021 4:17:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Apr 21, 2021 4:17:18 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Apr 21, 2021 4:17:18 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [12,948] ms
Apr 21, 2021 4:17:18 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-apr-8080"]
Apr 21, 2021 4:17:18 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 13012 ms
``` 

Is this failure due to alpine image vs normal tomcat image?
