### ISSUE TITLE
Unable to find these plug ins mentioned in the XNAT ML setup. 

### ISSUE THREAD

**Issue by DrRadiohead** [NrgXnat/xnat-docker-compose#76]
{
    "version": "1.0",
    "base": "xnat-data",
    "webapps": "org.nrg.xnat.web:xnat-web:1.8 -> ROOT.war",
    "plugins": [
        "org.nrg.xnatx.plugins:batch-launch:0.4.0",
        "org.nrg.xnatx.plugins:container-service:3.0.0:fat",
        "org.nrg.xnatx.plugins:dicom-query-retrieve:ML-BETA:xpl",
        "org.nrg.xnatx.plugins:xnatx-clara:1.0",
        "org.nrg.xnatx.plugins:xnatx-collection:1.0",
        "org.nrg.xnatx.plugins:ohif-viewer:3.0.0:fat"
    ]
}

**Comment by rherrick** [comment]
You need to update your `xnat-docker-compose`. The latest ML manifest for the [features/dependency-mgmt branch](https://github.com/nrgxnat/xnat-docker-compose/tree/features/dependency-mgmt) has different plugin and web app versions:

```json
{
    "version": "1.8.0",
    "base": "xnat-data",
    "webapps": "org.nrg.xnat.web:xnat-web:1.8.0 -> ROOT.war",
    "plugins": [
        "org.nrg.xnatx.plugins:batch-launch:0.4.0",
        "org.nrg.xnatx.plugins:container-service:3.0.0:fat",
        "org.nrg.xnatx.plugins:ml-plugin:1.0.0",
        "org.nrg.xnatx.plugins:datasets-plugin:1.0.0",
        "org.nrg.xnatx.plugins:ohif-viewer:3.0.0:fat"
    ]
}
```
