### ISSUE TITLE
[BUG] nginx startup doesn't find xnat-web service

### ISSUE THREAD

**Issue by jerdra** [NrgXnat/xnat-docker-compose#85]
**Describe the bug**
When using docker-compose up it looks like the xnat-nginx service doesn't always find/or is able to connect to the xnat-web service.

**To Reproduce**
1. Clone repository.
2. Use default.env as .env
3. Build via docker compose up
4. Shut down containers via docker compose down
5. Spin up containers again 

**Expected behavior**
The xnat-web service should be available by the time xnat-nginx is created. However the current docker-compose seems to launch xnat-nginx too early causing it to exit with code 1

**Screenshots**

**Docker server environment (please complete the following information):**
 - Host OS: ArchLinux 5.14.9-arch2-1
 - Docker version: 20.10.9
 - docker-compose version: 2.0.1

**Configuration:**
 - Branch of XNAT docker-compose project: master
 - Commit hash or tag: 624599f
 - Environment settings: default.env
 - Configuration:

**Additional context**
Switching `links` in the xnat-nginx compose to `depends_on` resolves the issue by forcing xnat-nginx to wait for the xnat-web service to be initialized first

**Comment by kelseym** [comment]
Fixed with #84
